/* src/state.rs — the dispatcher.

   Part of the C++ port of markdown-rs 1.0.0 (see src/markdown/readme.md).
   One arm per state, each calling the function of the same name. */

#include "markdown/construct.h"

namespace markdown {

State Call(Tokenizer* t, StateName name) {
    switch (name) {
        case StateName::AttentionStart:
            return AttentionStart(t);
        case StateName::AttentionInside:
            return AttentionInside(t);
        case StateName::AutolinkStart:
            return AutolinkStart(t);
        case StateName::AutolinkOpen:
            return AutolinkOpen(t);
        case StateName::AutolinkSchemeOrEmailAtext:
            return AutolinkSchemeOrEmailAtext(t);
        case StateName::AutolinkSchemeInsideOrEmailAtext:
            return AutolinkSchemeInsideOrEmailAtext(t);
        case StateName::AutolinkUrlInside:
            return AutolinkUrlInside(t);
        case StateName::AutolinkEmailAtSignOrDot:
            return AutolinkEmailAtSignOrDot(t);
        case StateName::AutolinkEmailAtext:
            return AutolinkEmailAtext(t);
        case StateName::AutolinkEmailValue:
            return AutolinkEmailValue(t);
        case StateName::AutolinkEmailLabel:
            return AutolinkEmailLabel(t);
        case StateName::BlankLineStart:
            return BlankLineStart(t);
        case StateName::BlankLineAfter:
            return BlankLineAfter(t);
        case StateName::BlockQuoteStart:
            return BlockQuoteStart(t);
        case StateName::BlockQuoteContStart:
            return BlockQuoteContStart(t);
        case StateName::BlockQuoteContBefore:
            return BlockQuoteContBefore(t);
        case StateName::BlockQuoteContAfter:
            return BlockQuoteContAfter(t);
        case StateName::BomStart:
            return BomStart(t);
        case StateName::BomInside:
            return BomInside(t);
        case StateName::CharacterEscapeStart:
            return CharacterEscapeStart(t);
        case StateName::CharacterEscapeInside:
            return CharacterEscapeInside(t);
        case StateName::CharacterReferenceStart:
            return CharacterReferenceStart(t);
        case StateName::CharacterReferenceOpen:
            return CharacterReferenceOpen(t);
        case StateName::CharacterReferenceNumeric:
            return CharacterReferenceNumeric(t);
        case StateName::CharacterReferenceValue:
            return CharacterReferenceValue(t);
        case StateName::CodeIndentedStart:
            return CodeIndentedStart(t);
        case StateName::CodeIndentedAtBreak:
            return CodeIndentedAtBreak(t);
        case StateName::CodeIndentedAfter:
            return CodeIndentedAfter(t);
        case StateName::CodeIndentedFurtherStart:
            return CodeIndentedFurtherStart(t);
        case StateName::CodeIndentedInside:
            return CodeIndentedInside(t);
        case StateName::CodeIndentedFurtherBegin:
            return CodeIndentedFurtherBegin(t);
        case StateName::CodeIndentedFurtherAfter:
            return CodeIndentedFurtherAfter(t);
        case StateName::ContentChunkStart:
            return ContentChunkStart(t);
        case StateName::ContentChunkInside:
            return ContentChunkInside(t);
        case StateName::ContentDefinitionBefore:
            return ContentDefinitionBefore(t);
        case StateName::ContentDefinitionAfter:
            return ContentDefinitionAfter(t);
        case StateName::DataStart:
            return DataStart(t);
        case StateName::DataInside:
            return DataInside(t);
        case StateName::DataAtBreak:
            return DataAtBreak(t);
        case StateName::DefinitionStart:
            return DefinitionStart(t);
        case StateName::DefinitionBefore:
            return DefinitionBefore(t);
        case StateName::DefinitionLabelAfter:
            return DefinitionLabelAfter(t);
        case StateName::DefinitionLabelNok:
            return DefinitionLabelNok(t);
        case StateName::DefinitionMarkerAfter:
            return DefinitionMarkerAfter(t);
        case StateName::DefinitionDestinationBefore:
            return DefinitionDestinationBefore(t);
        case StateName::DefinitionDestinationAfter:
            return DefinitionDestinationAfter(t);
        case StateName::DefinitionDestinationMissing:
            return DefinitionDestinationMissing(t);
        case StateName::DefinitionTitleBefore:
            return DefinitionTitleBefore(t);
        case StateName::DefinitionAfter:
            return DefinitionAfter(t);
        case StateName::DefinitionAfterWhitespace:
            return DefinitionAfterWhitespace(t);
        case StateName::DefinitionTitleBeforeMarker:
            return DefinitionTitleBeforeMarker(t);
        case StateName::DefinitionTitleAfter:
            return DefinitionTitleAfter(t);
        case StateName::DefinitionTitleAfterOptionalWhitespace:
            return DefinitionTitleAfterOptionalWhitespace(t);
        case StateName::DestinationStart:
            return DestinationStart(t);
        case StateName::DestinationEnclosedBefore:
            return DestinationEnclosedBefore(t);
        case StateName::DestinationEnclosed:
            return DestinationEnclosed(t);
        case StateName::DestinationEnclosedEscape:
            return DestinationEnclosedEscape(t);
        case StateName::DestinationRaw:
            return DestinationRaw(t);
        case StateName::DestinationRawEscape:
            return DestinationRawEscape(t);
        case StateName::DocumentStart:
            return DocumentStart(t);
        case StateName::DocumentBeforeFrontmatter:
            return DocumentBeforeFrontmatter(t);
        case StateName::DocumentContainerExistingBefore:
            return DocumentContainerExistingBefore(t);
        case StateName::DocumentContainerExistingAfter:
            return DocumentContainerExistingAfter(t);
        case StateName::DocumentContainerNewBefore:
            return DocumentContainerNewBefore(t);
        case StateName::DocumentContainerNewBeforeNotBlockQuote:
            return DocumentContainerNewBeforeNotBlockQuote(t);
        case StateName::DocumentContainerNewBeforeNotList:
            return DocumentContainerNewBeforeNotList(t);
        case StateName::DocumentContainerNewBeforeNotGfmFootnoteDefinition:
            return DocumentContainerNewBeforeNotGfmFootnoteDefinition(t);
        case StateName::DocumentContainerNewAfter:
            return DocumentContainerNewAfter(t);
        case StateName::DocumentContainersAfter:
            return DocumentContainersAfter(t);
        case StateName::DocumentFlowInside:
            return DocumentFlowInside(t);
        case StateName::DocumentFlowEnd:
            return DocumentFlowEnd(t);
        case StateName::FlowStart:
            return FlowStart(t);
        case StateName::FlowBeforeGfmTable:
            return FlowBeforeGfmTable(t);
        case StateName::FlowBeforeCodeIndented:
            return FlowBeforeCodeIndented(t);
        case StateName::FlowBeforeRaw:
            return FlowBeforeRaw(t);
        case StateName::FlowBeforeHtml:
            return FlowBeforeHtml(t);
        case StateName::FlowBeforeHeadingAtx:
            return FlowBeforeHeadingAtx(t);
        case StateName::FlowBeforeHeadingSetext:
            return FlowBeforeHeadingSetext(t);
        case StateName::FlowBeforeThematicBreak:
            return FlowBeforeThematicBreak(t);
        case StateName::FlowAfter:
            return FlowAfter(t);
        case StateName::FlowBlankLineBefore:
            return FlowBlankLineBefore(t);
        case StateName::FlowBlankLineAfter:
            return FlowBlankLineAfter(t);
        case StateName::FlowBeforeContent:
            return FlowBeforeContent(t);
        case StateName::FrontmatterStart:
            return FrontmatterStart(t);
        case StateName::FrontmatterOpenSequence:
            return FrontmatterOpenSequence(t);
        case StateName::FrontmatterOpenAfter:
            return FrontmatterOpenAfter(t);
        case StateName::FrontmatterAfter:
            return FrontmatterAfter(t);
        case StateName::FrontmatterContentStart:
            return FrontmatterContentStart(t);
        case StateName::FrontmatterContentInside:
            return FrontmatterContentInside(t);
        case StateName::FrontmatterContentEnd:
            return FrontmatterContentEnd(t);
        case StateName::FrontmatterCloseStart:
            return FrontmatterCloseStart(t);
        case StateName::FrontmatterCloseSequence:
            return FrontmatterCloseSequence(t);
        case StateName::FrontmatterCloseAfter:
            return FrontmatterCloseAfter(t);
        case StateName::GfmAutolinkLiteralProtocolStart:
            return GfmAutolinkLiteralProtocolStart(t);
        case StateName::GfmAutolinkLiteralProtocolAfter:
            return GfmAutolinkLiteralProtocolAfter(t);
        case StateName::GfmAutolinkLiteralProtocolPrefixInside:
            return GfmAutolinkLiteralProtocolPrefixInside(t);
        case StateName::GfmAutolinkLiteralProtocolSlashesInside:
            return GfmAutolinkLiteralProtocolSlashesInside(t);
        case StateName::GfmAutolinkLiteralWwwStart:
            return GfmAutolinkLiteralWwwStart(t);
        case StateName::GfmAutolinkLiteralWwwAfter:
            return GfmAutolinkLiteralWwwAfter(t);
        case StateName::GfmAutolinkLiteralWwwPrefixInside:
            return GfmAutolinkLiteralWwwPrefixInside(t);
        case StateName::GfmAutolinkLiteralWwwPrefixAfter:
            return GfmAutolinkLiteralWwwPrefixAfter(t);
        case StateName::GfmAutolinkLiteralDomainInside:
            return GfmAutolinkLiteralDomainInside(t);
        case StateName::GfmAutolinkLiteralDomainAtPunctuation:
            return GfmAutolinkLiteralDomainAtPunctuation(t);
        case StateName::GfmAutolinkLiteralDomainAfter:
            return GfmAutolinkLiteralDomainAfter(t);
        case StateName::GfmAutolinkLiteralPathInside:
            return GfmAutolinkLiteralPathInside(t);
        case StateName::GfmAutolinkLiteralPathAtPunctuation:
            return GfmAutolinkLiteralPathAtPunctuation(t);
        case StateName::GfmAutolinkLiteralPathAfter:
            return GfmAutolinkLiteralPathAfter(t);
        case StateName::GfmAutolinkLiteralTrail:
            return GfmAutolinkLiteralTrail(t);
        case StateName::GfmAutolinkLiteralTrailCharRefInside:
            return GfmAutolinkLiteralTrailCharRefInside(t);
        case StateName::GfmAutolinkLiteralTrailCharRefStart:
            return GfmAutolinkLiteralTrailCharRefStart(t);
        case StateName::GfmAutolinkLiteralTrailBracketAfter:
            return GfmAutolinkLiteralTrailBracketAfter(t);
        case StateName::GfmFootnoteDefinitionStart:
            return GfmFootnoteDefinitionStart(t);
        case StateName::GfmFootnoteDefinitionLabelBefore:
            return GfmFootnoteDefinitionLabelBefore(t);
        case StateName::GfmFootnoteDefinitionLabelAtMarker:
            return GfmFootnoteDefinitionLabelAtMarker(t);
        case StateName::GfmFootnoteDefinitionLabelInside:
            return GfmFootnoteDefinitionLabelInside(t);
        case StateName::GfmFootnoteDefinitionLabelEscape:
            return GfmFootnoteDefinitionLabelEscape(t);
        case StateName::GfmFootnoteDefinitionLabelAfter:
            return GfmFootnoteDefinitionLabelAfter(t);
        case StateName::GfmFootnoteDefinitionWhitespaceAfter:
            return GfmFootnoteDefinitionWhitespaceAfter(t);
        case StateName::GfmFootnoteDefinitionContStart:
            return GfmFootnoteDefinitionContStart(t);
        case StateName::GfmFootnoteDefinitionContBlank:
            return GfmFootnoteDefinitionContBlank(t);
        case StateName::GfmFootnoteDefinitionContFilled:
            return GfmFootnoteDefinitionContFilled(t);
        case StateName::GfmLabelStartFootnoteStart:
            return GfmLabelStartFootnoteStart(t);
        case StateName::GfmLabelStartFootnoteOpen:
            return GfmLabelStartFootnoteOpen(t);
        case StateName::GfmTaskListItemCheckStart:
            return GfmTaskListItemCheckStart(t);
        case StateName::GfmTaskListItemCheckInside:
            return GfmTaskListItemCheckInside(t);
        case StateName::GfmTaskListItemCheckClose:
            return GfmTaskListItemCheckClose(t);
        case StateName::GfmTaskListItemCheckAfter:
            return GfmTaskListItemCheckAfter(t);
        case StateName::GfmTaskListItemCheckAfterSpaceOrTab:
            return GfmTaskListItemCheckAfterSpaceOrTab(t);
        case StateName::GfmTableStart:
            return GfmTableStart(t);
        case StateName::GfmTableHeadRowBefore:
            return GfmTableHeadRowBefore(t);
        case StateName::GfmTableHeadRowStart:
            return GfmTableHeadRowStart(t);
        case StateName::GfmTableHeadRowBreak:
            return GfmTableHeadRowBreak(t);
        case StateName::GfmTableHeadRowData:
            return GfmTableHeadRowData(t);
        case StateName::GfmTableHeadRowEscape:
            return GfmTableHeadRowEscape(t);
        case StateName::GfmTableHeadDelimiterStart:
            return GfmTableHeadDelimiterStart(t);
        case StateName::GfmTableHeadDelimiterBefore:
            return GfmTableHeadDelimiterBefore(t);
        case StateName::GfmTableHeadDelimiterCellBefore:
            return GfmTableHeadDelimiterCellBefore(t);
        case StateName::GfmTableHeadDelimiterValueBefore:
            return GfmTableHeadDelimiterValueBefore(t);
        case StateName::GfmTableHeadDelimiterLeftAlignmentAfter:
            return GfmTableHeadDelimiterLeftAlignmentAfter(t);
        case StateName::GfmTableHeadDelimiterFiller:
            return GfmTableHeadDelimiterFiller(t);
        case StateName::GfmTableHeadDelimiterRightAlignmentAfter:
            return GfmTableHeadDelimiterRightAlignmentAfter(t);
        case StateName::GfmTableHeadDelimiterCellAfter:
            return GfmTableHeadDelimiterCellAfter(t);
        case StateName::GfmTableHeadDelimiterNok:
            return GfmTableHeadDelimiterNok(t);
        case StateName::GfmTableBodyRowStart:
            return GfmTableBodyRowStart(t);
        case StateName::GfmTableBodyRowBreak:
            return GfmTableBodyRowBreak(t);
        case StateName::GfmTableBodyRowData:
            return GfmTableBodyRowData(t);
        case StateName::GfmTableBodyRowEscape:
            return GfmTableBodyRowEscape(t);
        case StateName::HardBreakEscapeStart:
            return HardBreakEscapeStart(t);
        case StateName::HardBreakEscapeAfter:
            return HardBreakEscapeAfter(t);
        case StateName::HeadingAtxStart:
            return HeadingAtxStart(t);
        case StateName::HeadingAtxBefore:
            return HeadingAtxBefore(t);
        case StateName::HeadingAtxSequenceOpen:
            return HeadingAtxSequenceOpen(t);
        case StateName::HeadingAtxAtBreak:
            return HeadingAtxAtBreak(t);
        case StateName::HeadingAtxSequenceFurther:
            return HeadingAtxSequenceFurther(t);
        case StateName::HeadingAtxData:
            return HeadingAtxData(t);
        case StateName::HeadingSetextStart:
            return HeadingSetextStart(t);
        case StateName::HeadingSetextBefore:
            return HeadingSetextBefore(t);
        case StateName::HeadingSetextInside:
            return HeadingSetextInside(t);
        case StateName::HeadingSetextAfter:
            return HeadingSetextAfter(t);
        case StateName::HtmlFlowStart:
            return HtmlFlowStart(t);
        case StateName::HtmlFlowBefore:
            return HtmlFlowBefore(t);
        case StateName::HtmlFlowOpen:
            return HtmlFlowOpen(t);
        case StateName::HtmlFlowDeclarationOpen:
            return HtmlFlowDeclarationOpen(t);
        case StateName::HtmlFlowCommentOpenInside:
            return HtmlFlowCommentOpenInside(t);
        case StateName::HtmlFlowCdataOpenInside:
            return HtmlFlowCdataOpenInside(t);
        case StateName::HtmlFlowTagCloseStart:
            return HtmlFlowTagCloseStart(t);
        case StateName::HtmlFlowTagName:
            return HtmlFlowTagName(t);
        case StateName::HtmlFlowBasicSelfClosing:
            return HtmlFlowBasicSelfClosing(t);
        case StateName::HtmlFlowCompleteClosingTagAfter:
            return HtmlFlowCompleteClosingTagAfter(t);
        case StateName::HtmlFlowCompleteEnd:
            return HtmlFlowCompleteEnd(t);
        case StateName::HtmlFlowCompleteAttributeNameBefore:
            return HtmlFlowCompleteAttributeNameBefore(t);
        case StateName::HtmlFlowCompleteAttributeName:
            return HtmlFlowCompleteAttributeName(t);
        case StateName::HtmlFlowCompleteAttributeNameAfter:
            return HtmlFlowCompleteAttributeNameAfter(t);
        case StateName::HtmlFlowCompleteAttributeValueBefore:
            return HtmlFlowCompleteAttributeValueBefore(t);
        case StateName::HtmlFlowCompleteAttributeValueQuoted:
            return HtmlFlowCompleteAttributeValueQuoted(t);
        case StateName::HtmlFlowCompleteAttributeValueQuotedAfter:
            return HtmlFlowCompleteAttributeValueQuotedAfter(t);
        case StateName::HtmlFlowCompleteAttributeValueUnquoted:
            return HtmlFlowCompleteAttributeValueUnquoted(t);
        case StateName::HtmlFlowCompleteAfter:
            return HtmlFlowCompleteAfter(t);
        case StateName::HtmlFlowBlankLineBefore:
            return HtmlFlowBlankLineBefore(t);
        case StateName::HtmlFlowContinuation:
            return HtmlFlowContinuation(t);
        case StateName::HtmlFlowContinuationDeclarationInside:
            return HtmlFlowContinuationDeclarationInside(t);
        case StateName::HtmlFlowContinuationAfter:
            return HtmlFlowContinuationAfter(t);
        case StateName::HtmlFlowContinuationStart:
            return HtmlFlowContinuationStart(t);
        case StateName::HtmlFlowContinuationBefore:
            return HtmlFlowContinuationBefore(t);
        case StateName::HtmlFlowContinuationCommentInside:
            return HtmlFlowContinuationCommentInside(t);
        case StateName::HtmlFlowContinuationRawTagOpen:
            return HtmlFlowContinuationRawTagOpen(t);
        case StateName::HtmlFlowContinuationRawEndTag:
            return HtmlFlowContinuationRawEndTag(t);
        case StateName::HtmlFlowContinuationClose:
            return HtmlFlowContinuationClose(t);
        case StateName::HtmlFlowContinuationCdataInside:
            return HtmlFlowContinuationCdataInside(t);
        case StateName::HtmlFlowContinuationStartNonLazy:
            return HtmlFlowContinuationStartNonLazy(t);
        case StateName::HtmlTextStart:
            return HtmlTextStart(t);
        case StateName::HtmlTextOpen:
            return HtmlTextOpen(t);
        case StateName::HtmlTextDeclarationOpen:
            return HtmlTextDeclarationOpen(t);
        case StateName::HtmlTextTagCloseStart:
            return HtmlTextTagCloseStart(t);
        case StateName::HtmlTextTagClose:
            return HtmlTextTagClose(t);
        case StateName::HtmlTextTagCloseBetween:
            return HtmlTextTagCloseBetween(t);
        case StateName::HtmlTextTagOpen:
            return HtmlTextTagOpen(t);
        case StateName::HtmlTextTagOpenBetween:
            return HtmlTextTagOpenBetween(t);
        case StateName::HtmlTextTagOpenAttributeName:
            return HtmlTextTagOpenAttributeName(t);
        case StateName::HtmlTextTagOpenAttributeNameAfter:
            return HtmlTextTagOpenAttributeNameAfter(t);
        case StateName::HtmlTextTagOpenAttributeValueBefore:
            return HtmlTextTagOpenAttributeValueBefore(t);
        case StateName::HtmlTextTagOpenAttributeValueQuoted:
            return HtmlTextTagOpenAttributeValueQuoted(t);
        case StateName::HtmlTextTagOpenAttributeValueQuotedAfter:
            return HtmlTextTagOpenAttributeValueQuotedAfter(t);
        case StateName::HtmlTextTagOpenAttributeValueUnquoted:
            return HtmlTextTagOpenAttributeValueUnquoted(t);
        case StateName::HtmlTextCdata:
            return HtmlTextCdata(t);
        case StateName::HtmlTextCdataOpenInside:
            return HtmlTextCdataOpenInside(t);
        case StateName::HtmlTextCdataClose:
            return HtmlTextCdataClose(t);
        case StateName::HtmlTextCdataEnd:
            return HtmlTextCdataEnd(t);
        case StateName::HtmlTextCommentOpenInside:
            return HtmlTextCommentOpenInside(t);
        case StateName::HtmlTextComment:
            return HtmlTextComment(t);
        case StateName::HtmlTextCommentClose:
            return HtmlTextCommentClose(t);
        case StateName::HtmlTextCommentEnd:
            return HtmlTextCommentEnd(t);
        case StateName::HtmlTextDeclaration:
            return HtmlTextDeclaration(t);
        case StateName::HtmlTextEnd:
            return HtmlTextEnd(t);
        case StateName::HtmlTextInstruction:
            return HtmlTextInstruction(t);
        case StateName::HtmlTextInstructionClose:
            return HtmlTextInstructionClose(t);
        case StateName::HtmlTextLineEndingBefore:
            return HtmlTextLineEndingBefore(t);
        case StateName::HtmlTextLineEndingAfter:
            return HtmlTextLineEndingAfter(t);
        case StateName::HtmlTextLineEndingAfterPrefix:
            return HtmlTextLineEndingAfterPrefix(t);
        case StateName::LabelStart:
            return LabelStart(t);
        case StateName::LabelAtBreak:
            return LabelAtBreak(t);
        case StateName::LabelEolAfter:
            return LabelEolAfter(t);
        case StateName::LabelEscape:
            return LabelEscape(t);
        case StateName::LabelInside:
            return LabelInside(t);
        case StateName::LabelNok:
            return LabelNok(t);
        case StateName::LabelEndStart:
            return LabelEndStart(t);
        case StateName::LabelEndAfter:
            return LabelEndAfter(t);
        case StateName::LabelEndResourceStart:
            return LabelEndResourceStart(t);
        case StateName::LabelEndResourceBefore:
            return LabelEndResourceBefore(t);
        case StateName::LabelEndResourceOpen:
            return LabelEndResourceOpen(t);
        case StateName::LabelEndResourceDestinationAfter:
            return LabelEndResourceDestinationAfter(t);
        case StateName::LabelEndResourceDestinationMissing:
            return LabelEndResourceDestinationMissing(t);
        case StateName::LabelEndResourceBetween:
            return LabelEndResourceBetween(t);
        case StateName::LabelEndResourceTitleAfter:
            return LabelEndResourceTitleAfter(t);
        case StateName::LabelEndResourceEnd:
            return LabelEndResourceEnd(t);
        case StateName::LabelEndOk:
            return LabelEndOk(t);
        case StateName::LabelEndNok:
            return LabelEndNok(t);
        case StateName::LabelEndReferenceFull:
            return LabelEndReferenceFull(t);
        case StateName::LabelEndReferenceFullAfter:
            return LabelEndReferenceFullAfter(t);
        case StateName::LabelEndReferenceFullMissing:
            return LabelEndReferenceFullMissing(t);
        case StateName::LabelEndReferenceNotFull:
            return LabelEndReferenceNotFull(t);
        case StateName::LabelEndReferenceCollapsed:
            return LabelEndReferenceCollapsed(t);
        case StateName::LabelEndReferenceCollapsedOpen:
            return LabelEndReferenceCollapsedOpen(t);
        case StateName::LabelStartImageStart:
            return LabelStartImageStart(t);
        case StateName::LabelStartImageOpen:
            return LabelStartImageOpen(t);
        case StateName::LabelStartImageAfter:
            return LabelStartImageAfter(t);
        case StateName::LabelStartLinkStart:
            return LabelStartLinkStart(t);
        case StateName::ListItemStart:
            return ListItemStart(t);
        case StateName::ListItemBefore:
            return ListItemBefore(t);
        case StateName::ListItemBeforeOrdered:
            return ListItemBeforeOrdered(t);
        case StateName::ListItemBeforeUnordered:
            return ListItemBeforeUnordered(t);
        case StateName::ListItemValue:
            return ListItemValue(t);
        case StateName::ListItemMarker:
            return ListItemMarker(t);
        case StateName::ListItemMarkerAfter:
            return ListItemMarkerAfter(t);
        case StateName::ListItemAfter:
            return ListItemAfter(t);
        case StateName::ListItemMarkerAfterFilled:
            return ListItemMarkerAfterFilled(t);
        case StateName::ListItemWhitespace:
            return ListItemWhitespace(t);
        case StateName::ListItemPrefixOther:
            return ListItemPrefixOther(t);
        case StateName::ListItemWhitespaceAfter:
            return ListItemWhitespaceAfter(t);
        case StateName::ListItemContStart:
            return ListItemContStart(t);
        case StateName::ListItemContBlank:
            return ListItemContBlank(t);
        case StateName::ListItemContFilled:
            return ListItemContFilled(t);
        case StateName::NonLazyContinuationStart:
            return NonLazyContinuationStart(t);
        case StateName::NonLazyContinuationAfter:
            return NonLazyContinuationAfter(t);
        case StateName::ParagraphStart:
            return ParagraphStart(t);
        case StateName::ParagraphLineStart:
            return ParagraphLineStart(t);
        case StateName::ParagraphInside:
            return ParagraphInside(t);
        case StateName::RawFlowStart:
            return RawFlowStart(t);
        case StateName::RawFlowBeforeSequenceOpen:
            return RawFlowBeforeSequenceOpen(t);
        case StateName::RawFlowSequenceOpen:
            return RawFlowSequenceOpen(t);
        case StateName::RawFlowInfoBefore:
            return RawFlowInfoBefore(t);
        case StateName::RawFlowInfo:
            return RawFlowInfo(t);
        case StateName::RawFlowMetaBefore:
            return RawFlowMetaBefore(t);
        case StateName::RawFlowMeta:
            return RawFlowMeta(t);
        case StateName::RawFlowAtNonLazyBreak:
            return RawFlowAtNonLazyBreak(t);
        case StateName::RawFlowCloseStart:
            return RawFlowCloseStart(t);
        case StateName::RawFlowBeforeSequenceClose:
            return RawFlowBeforeSequenceClose(t);
        case StateName::RawFlowSequenceClose:
            return RawFlowSequenceClose(t);
        case StateName::RawFlowAfterSequenceClose:
            return RawFlowAfterSequenceClose(t);
        case StateName::RawFlowContentBefore:
            return RawFlowContentBefore(t);
        case StateName::RawFlowContentStart:
            return RawFlowContentStart(t);
        case StateName::RawFlowBeforeContentChunk:
            return RawFlowBeforeContentChunk(t);
        case StateName::RawFlowContentChunk:
            return RawFlowContentChunk(t);
        case StateName::RawFlowAfter:
            return RawFlowAfter(t);
        case StateName::RawTextStart:
            return RawTextStart(t);
        case StateName::RawTextSequenceOpen:
            return RawTextSequenceOpen(t);
        case StateName::RawTextBetween:
            return RawTextBetween(t);
        case StateName::RawTextData:
            return RawTextData(t);
        case StateName::RawTextSequenceClose:
            return RawTextSequenceClose(t);
        case StateName::SpaceOrTabStart:
            return SpaceOrTabStart(t);
        case StateName::SpaceOrTabInside:
            return SpaceOrTabInside(t);
        case StateName::SpaceOrTabAfter:
            return SpaceOrTabAfter(t);
        case StateName::SpaceOrTabEolStart:
            return SpaceOrTabEolStart(t);
        case StateName::SpaceOrTabEolAfterFirst:
            return SpaceOrTabEolAfterFirst(t);
        case StateName::SpaceOrTabEolAfterEol:
            return SpaceOrTabEolAfterEol(t);
        case StateName::SpaceOrTabEolAtEol:
            return SpaceOrTabEolAtEol(t);
        case StateName::SpaceOrTabEolAfterMore:
            return SpaceOrTabEolAfterMore(t);
        case StateName::StringStart:
            return StringStart(t);
        case StateName::StringBefore:
            return StringBefore(t);
        case StateName::StringBeforeData:
            return StringBeforeData(t);
        case StateName::TextStart:
            return TextStart(t);
        case StateName::TextBefore:
            return TextBefore(t);
        case StateName::TextBeforeHtml:
            return TextBeforeHtml(t);
        case StateName::TextBeforeHardBreakEscape:
            return TextBeforeHardBreakEscape(t);
        case StateName::TextBeforeLabelStartLink:
            return TextBeforeLabelStartLink(t);
        case StateName::TextBeforeData:
            return TextBeforeData(t);
        case StateName::ThematicBreakStart:
            return ThematicBreakStart(t);
        case StateName::ThematicBreakBefore:
            return ThematicBreakBefore(t);
        case StateName::ThematicBreakSequence:
            return ThematicBreakSequence(t);
        case StateName::ThematicBreakAtBreak:
            return ThematicBreakAtBreak(t);
        case StateName::TitleStart:
            return TitleStart(t);
        case StateName::TitleBegin:
            return TitleBegin(t);
        case StateName::TitleAfterEol:
            return TitleAfterEol(t);
        case StateName::TitleAtBreak:
            return TitleAtBreak(t);
        case StateName::TitleEscape:
            return TitleEscape(t);
        case StateName::TitleInside:
            return TitleInside(t);
        case StateName::TitleNok:
            return TitleNok(t);
    }
    // Every state is named above; the compiler cannot see that.
    return StateNok();
}

} // namespace markdown
