/* Generated by cmd/update-win-shaders.ts. Do not edit.
   source-sha256: 1a82d9b62363579cc0ba0c8dc7ef35fbb3199729c376cdcc3bd43ccd1df9b11c
   encoding: basE95 over printable ASCII space through ~ */

#include "gpui/paintgpu.h"

#if GPUI_OS_WINDOWS && WIN_BACKEND_GPU
namespace gpui {
namespace gpuw {

extern const char kShaderVSQuad95[] = R"GPUI95(
.Ea8f_/IxQo|.D79qZ{?;cKNw#   Cc( uU    )!  uU" +K !  &6  ]=0 +K"NkAt0! j*    M!  @   Kk!   f&2v:K&&``
.C   ]+c9TH    #   `   M-  +K$   8       ``'   %   !!  b"    8       `   j*    f"
.                        U5    $   Ee~lI3Z 0bh2}LuDDvoZO%  A!  +K7   @             ^   (   00%   8
.       ""  +KA       b"  j*    ##      Ss5v5v!   uu5vT5    ]-  j*    "       U5"       4v5v@!  ``5v5
.v/   XXo<>dfxOTJn@@C]$MK:<voZ 26v! " 0                             q%  GGiy5$wgoZa/        ,   $   (
.(!     6v5v5v?   pp5v5v#   88,b2\HRhODvB^|O. KR<O. n[L/3GT SGU $$E%6v                            eE8
.   LIli(m&fr\hOA@PD5LX5lo00h2u_C:<voZ:0  U5&       B2  U5&   $   Z2  U5&   (   n2  U5&   ,   #3  U5&
.   0   /3  U5&   4   4   ` ``    # i)                    .n+ 6v]Wf9SE\Iq~x*xPM#<8 TH& <"z+ZRFH(WZrEJ
.A^Sq59wJ9, |S+QkX  +K    @   eE        ,   @       6vA!  e%        !   "   @   E%( 6v'>ad,B)WS(g8d 0
.d*@OFd)^aN22\ |;["h!:`c&}  uU    (   iI      6v    8       ``#   z*            &   @   00""  f"  0
.       +K!   (   00, +KG!          ``    (   **  U5c   $       @@    &   %%  U50   "       ((    !
.   \   b"! @@        !!  z:    /   kK  U5        P   00  6v10  kK  z:        P   00    *$  u5  00
.        8   I)  +K'   *R5`RrT^Zfto2EuUo%a68I/}>vU4_nd;]=$'@79A@   H " m5  z:c VvL U5k+rK      !   ;;
.  ( I)$     00    # A!^5`     00    P U5##n*E%    $   `(  EcD!!     $   $d  CKa5@ (   qQ! fv&6@ (
.   qQ! fv26@ 0   qQ! fv26@ 8   qQ! fv26@ @   qQ! fv26@ H   qQ! fva5@ P   qQ! fv&6@ P   qQ! fv26@ X
.   uU! KK!   T$  |xwv      $ "                 +Kuv  ww, 0     $$;K      $ " @   00            Kk! B
.") @     #C  !     H b"      % d$b `     z:A!"     ( ( b"  U5  z:4$E%    +KA 0     A!`     jJ  Kk/
.         h!@@(w%$r2|d, )%A!@   uUb"$ !   0 0     6v&u@     Cc  gwP 0     $$/K      znb"`   ``A!( "
.   d$  z*# $ "   fFZ5      f C!        6v, 88Q!I%    +K" 0 (   ` `     +K" "     m.# f&Xv`     &f  -
.Ka   @   b"b"      % $     vx# f&R ` @   00w 8v    0 (     =%  tt        U5& 00*"b"`   ``_#( "   ` @
.     55  Kk'         C @ (       kKa5@ (   3SK !     z"b",L  U5    :"+Kzxwv+K!   _gF%    +K- M-@0r*E
.%    H%@ 0   TT" G7%$& \@71j*T%$ "   a!n*E%  6v6v  A!  >~tx      Q#``c!+(eEcS9 2*I%$$  +Kl*@ (   A!A
.!  *   xli"    Kk4 n.J@!!d$fS7v26@ @   M-` ,K    ( ( +K  6v&u@     TT" G7%$& \@71j*T%$ %   a!n*E%  6
.v6v  $$  >~tx      Q#``c!+(eEcS9 2*E%A!  +Kl*@ (   A!A!  (   xli"        E%$"`     00@ -Ka   0   006
.!8v    4$6vGcA!7v!   z"b"    ``_#(     W7+KU5    :"+KEcD!,K#   !Qm*E%    ? E%5} 6jV$   ,   8       6
.v!   2   @   00    !                                   !!                b"
.                                                                                  )GPUI95";
extern const int kShaderVSQuadSize = 2248;
uint8_t kShaderVSQuadBytes[2248] = {};

extern const char kShaderPSQuad95[] = R"GPUI95(
.Ea8fuE4Z#>[9i+9Sx~W=\{()&   XX7 U5!   2"  M-"   f   t,  eE6 +K"NkAHD            8   pp    C#5v\5##+K
.%   %|^|&%  @@    (   a!  88  6v!       TT  @@                      (   A!  +KH   (   C#  +K    4v5v
.a"  U5    T   [;! +K    4   b"  Kk5v5v7   A!  U5#   `Dj@9Lc`%L+cQ[Y `RQ]%U9$(XcO9psF@1l)#;6RG%ESHbTP
.?V4O.BIw:nqDI9a>&m<|0O,APP-Y63\+  M-    "   J*      U5    ,       Kk!   M%          6v!   (   $$& 6v
.@   "       00    !   ""# #C(           $$  +K    (l! Q1$ +K        $$  ``    (l! E%" +K        ""
.  +K    $F  b"! @@        !!  z:    WH  Ww  U5        P   00  6v%$  u5  M-        8   ((  6v%$  M%
.  ""      6v!   X   44\ +K'>!$r]pW`/RE/!IYe=,IkQ"N00A-Z4L#wg!:`cw.  j*    0   j*            P
.       +K'   *R5`/'=j=dJ"'oBXL<r.q+  M-  00C   `6U5\\  8 @@0     ;[P @ eE0 $   9Yk!  3(E%6vD!`   z:C
..  <x``aAVvU5    ,$,KyxWvU5    ,$,KDcc 7v    ,$,KDcc ,K!   8(8vDca ! !   ,$,KDcc ,K"   8(8vDc` 7v!
.   ,$,KyxWv+K!   ,$,KDcc ,K#   P(6vDcD!!     D$6vb"  j*& I)*"b"    ``%)0 8   /OVvU5!   &"+K{x7v
.      znc"C#  ``>*0 8   HH  cK$ 0     <<6v      4 A!    ``# d$2 `     &f  "     p E%    6v' I)h b"
.    U5' (     C#U5      - P@C#U5        Kk&&U5      UKA!A!  E%E%    ppW$  UP  "     p E%      $ I)I!
.b"    U5! (     @ @ z:    ? P@h(U5      e @@Ra  eEd<5 2*E%A!  +K{*@ P   >~tx+K      h"    6v# d$T"`
. 0   003!8v    Euq*j*    = KkK++K      " "     uU# $ !   2"b")f  "     T$6vEcD!!     [cF%A!  +K/ b"t
. +K+K  ww8 0     $$+K      $ "         6v        pp  Gw( 0     <<6v      T A!    pp! #": `     3S! B
."1 @     .n` ,K    S#G%A!  ``, r2r"E%    +K& 0     f&;K6v      U5NL7v      znc",L  U5    CKG%""! U5
.      +K{x7v      h<b"    ``x$(     Q1  q5" ( "   S3+K      t A!    00# d$2 ` 0   z:  8v    ( (
.     6v& M-0(b"    ``x$(     ` @                   ``# r2U%E%    +K@'0     ddKv      W!U5ML6v      t
. A!        B"A @     XX  !     H b"`       E%B `     &f  -Ka       z:! "       $ |x6v      T A!&6
.        ! !     _   Gw( 0     Q16v      jvA!A!    b"b"1 @     #C  a`@       A!A!    tt    x66v
.      T A!&6        J `     }]! ##1 @ (   M-  !     )!b"    U5% (     22  i5< (     8xa5U5    -!U5-,
.6vU5    J"c"A!  U5" A!` +KcA6v+K    8 b"    U5U5  (   ""            **  x*" $ "   D$j*j*    * ` @
.   Ss6v!!- @ 0   &f  ww8 0 (   Y9mvU5    ( $     Kk_]sb[b$W2!    ' eEH(j*00    qKA!@   @@y $ "   R"
.  L%" 7v    z"b"""  ``( ( &   99  i50 ( $   S3+K+K      +Ke"7v+K    J"b"A!  j*U5    ``de  Gw( 0 (
.   <<6v+K    )!b"A!  U5p*z:U%E%b"  +K. 0 h"  A!  U5# ( $   @ @     55R j*L++K+K    J"b"A!  U5# ( $
.   h(]5+K      ! L++K+K    )!b",L  +K    $ $     ^"  E%B ` @   &f  -Ka   @   z:! " !   \$6vqM  ,K
.    p E%b"  +K* 0 (   Q16v+K    :"+KoM# !     #+H%b"  +K- M-Q!E%A!  +Kx*@ 0   88  0 ( r2Q!E%b"  +K"
. 0     ` ` +K    ^ !af&+K+K    v"+K^y! KkIYJ r"E%A!  +K{*@ P   ]==%,K      Q%    +K- M-#3j*      dA`
. @   ;[! a!) @ (   .n` 7v    h +K+K  Gw$ 0     f&+K      " " ""      b"9 @ 0   >~Vv@@0   <   ddkv``!
.       NL7v+K    _gH%((  +KN-@ Q%  I)  +K' eE++U5U5    fZb"A!  ``( ( $   %%  x*! $ "   k+U5U5    M!A
.!`   U5# d$2 ` @   z:  " !   ( ( 2r!c"2DvKk&&U5U5    t A!`   uU  $ "       XP' 8v!   !Qq*(("   !   !
.Qq*00    R j*Rq+K+K    8 b"A!  ``l$( &   W7IK+K    >"+KGc# ,K    P E%    +K3&0 (   DDhv+K    :"+KoM#
. !     <dF%A!  +K- M-r"E%A!  U5+K    +K8Y  Vv* E%i!6vKk  Gw$ 0     Q16vU5    H b"`   uU# I)h b"`   j
.*U5      f&+K      : !af&+KU5    B"+KFcB!!     8 b"    ``T"(     22  i5z*0     f&+K      =!U5wW/'?}2
.   g!  A!        %   K#  f&  U5!   4   b"                          (                     z:  6v!   (
.                                                                         )GPUI95";
extern const int kShaderPSQuadSize = 3028;
uint8_t kShaderPSQuadBytes[3028] = {};

extern const char kShaderVSTri95[] = R"GPUI95(
.Ea8f#3Ewyz&{%~YK#JoAib]h!   n." z:    T   }]    /   9#  Pp  PP=;@ON&  @   U5&   !   **    SK5vF%D 9y
.  j*[V:bR"  00    $   p   ,,  +K!       ~>                          $   `   KkLDk|4OsFKk"   !   J*
.  +K            00#       @   A!    .       &v5vi*    4v5v@!  6v@   0   b"        1!      tt5v5v
.    &v5vi*    lBq\\j1pSF5!GOREwV7$YYJ?- !!A!j*                            ;[& 6v064OBv]Wf9SE\Iq~x*xP
.M#<8 TH& <"z+ZRFH(WZrEJA^Sq59wJ9, J?!D*XzlU1  00    (   M-            8       ``""  g#            #
.   0   HH9!6vO           ``    (   **>   d:,9^<GU]!>fFSJ,% cN"2LX_8s"HXr)GN0   (   b"  +K&       0
.   ((        \   .n            !!  E%  6v'   :*            ,   A!  Kk!   V"  @       6v!   8   $$8 `
.`.Z6x$j#gzRh2W 8r{W_8,KA7!)AgJWI!'odPVL<W  6vW5  r   q1$ RP% b"LFf"    E%  6vO 00H(n*    6vO 00hH]5j
.*     "``llWv+K    @$  mlwv      "   "B  a5)+0 $   $d  CK26@ 0   qQ! fva5@ 8   uU! KK    T$  |xwv
.      $ "                 +KEF  b"9 @     >~Vv      M!f"          9 PP##r*      % @     A!A!    6v"
. "     m.# f&Xv`     &f  -Ka       b"b"      % $     Ac& f&)%B!@   @@)%$ !   ))  t*T%$ "   k+d5U5
.    -!U5bAvv``    z"c"    ``' A!=7 +E;"   "   $       Kk    &           6v
.                                                      A!
.                                                                                 )GPUI95";
extern const int kShaderVSTriSize = 1112;
uint8_t kShaderVSTriBytes[1112] = {};

extern const char kShaderPSTri95[] = R"GPUI95(
.Ea8fhX~QqQR,hLB[q9>`7*C-9   uU8 6v"   D$  +K"   k   n.  Kk) 6v"NkAt0                pp    C#5v\5##Kk
.!   %|^|&%  @@    (   a!  88  6v!       y92)=jhm`BY3&V6.o*)A7}s*I6I~.BIw:nqDI9a>&m<|0O,APP-Y63V%  b"
.  6v    )!      b"  +K!       44    =           @@    "   ;{' uU'           ((  6v    (l! .n! +K
.        $$  ``    L@  Y9(o&;CTs($gkm1KU4_nd;uUo%a68I/}>v*5{nB:L   0   U5    0           ``        **
.  ``.ZU7E0.UDODvoZgy_+"6$   4   r"  Gg0 3K#+00hH]5j*    <x``llWv+K    ,$,KDc` ,K!   P(6vDcD!!     D$
.6v`   j*& I)*"b"    ``M%( &   W7;K+K    &"+K{x7v      znc"A!  ``f&( &   44  q5" (     ..+K      4 A!
.    ``# d$2 `     &f  "     p E%    6v' I)h b"    U5' (     C#U5      - P@C#U5      X KkFFKK      "v
.c"`   ``.&( "   22  i5z*0     'GVvU5    Z"+KY9?.D<U!  Q!  b"        0   ""        #   0
.                                                     j*
.                                                                                  )GPUI95";
extern const int kShaderPSTriSize = 788;
uint8_t kShaderPSTriBytes[788] = {};

} // namespace gpuw
} // namespace gpui
#endif
